-
  branches:
    except:
      - release
  init:
    - cmd: "set branch=%APPVEYOR_REPO_BRANCH%"
    - cmd: "echo branch:%branch%"
    - cmd: "set newVersion=1.0.%APPVEYOR_BUILD_NUMBER%-%branch%"
    - cmd: "echo newVersion:%newVersion%"
    - cmd: "set versonSuffix=%APPVEYOR_BUILD_NUMBER%-%branch%"    
    - cmd: "echo versonSuffix:%versonSuffix%"
    - cmd: appveyor UpdateBuild -Version "%newVersion%"

  skip_tags: true

  before_build:
    - nuget install OpenCover -ExcludeVersion -OutputDirectory "packages"
    - choco install opencover.portable
    - choco install codecov
    - cmd: dotnet tool install --global altcover.global

  configuration: Debug

  image: Visual Studio 2019

  build_script:
    - cmd: dotnet restore -v n  ./src/serilog-sinks-graylog.sln
    - cmd: dotnet build  -v n -c Debug ./src/serilog-sinks-graylog.sln
    - cmd: dotnet pack -v n --include-symbols --include-source -o "./artifacts" --version-suffix Beta -p:SymbolPackageFormat=snupkg ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj
    - cmd: dotnet pack -v n --include-symbols --include-source -o "./artifacts" --version-suffix Beta -p:SymbolPackageFormat=snupkg ./src/Serilog.Sinks.Graylog.Batching/Serilog.Sinks.Graylog.Batching.csproj

  test:
    categories:
      except:
        - Integration

  test_script:
    - dotnet test ./src/Serilog.Sinks.Graylog.Core.Tests --filter Category!=Integration /p:AltCover=true
    - dotnet test ./src/Serilog.Sinks.Graylog.Tests --filter Category!=Integration /p:AltCover=true

  after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "./src/Serilog.Sinks.Graylog.Core.Tests/coverage.xml" -t cd3f1ab1-60c6-4848-824b-466b93321d96
    - codecov -f "./src/Serilog.Sinks.Graylog.Tests/coverage.xml" -t cd3f1ab1-60c6-4848-824b-466b93321d96
  
  artifacts:
    - path: "./artifacts/*.*"
-
  branches:
    only:
      - release

  configuration: Release

  image: Visual Studio 2019

  build:
    publish_nuget_symbols: true
    use_snupkg_format: true

  build_script:
    - cmd: dotnet restore -v n  ./src/serilog-sinks-graylog.sln
    - cmd: dotnet build  -v n -c Release ./src/serilog-sinks-graylog.sln
    - cmd: dotnet pack -v n --include-symbols --include-source -o "./artifacts" -p:SymbolPackageFormat=snupkg ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj
    - cmd: dotnet pack -v n --include-symbols --include-source -o "./artifacts" -p:SymbolPackageFormat=snupkg ./src/Serilog.Sinks.Graylog.Batching/Serilog.Sinks.Graylog.Batching.csproj
  test:
    categories:
      except:
        - Integration
  
  artifacts:
    - path: "./artifacts/*.*"

  deploy:
    provider: NuGet
    api_key:
      secure: Ok7AB6H7Sx08sw3JvdS2LOf84yyAuegDsl4pD4HN0aPSYl2Wt0SA9Y69n7COIrkO
      skip_symbols: false
      artifact: /.*.*
